// <auto-generated />
using System;
using AV.DA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AV.DA.Migrations
{
    [DbContext(typeof(AVDBContext))]
    partial class AVDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AV.BO.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadAsientosMesa")
                        .HasColumnType("Integer");

                    b.Property<int>("CantidadMesas")
                        .HasColumnType("Integer");

                    b.Property<string>("CriterioAsignacion")
                        .IsRequired()
                        .HasColumnType("VarChar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("VarChar(300)");

                    b.Property<string>("EmpresaCreadora")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("VarChar(20)");

                    b.Property<byte[]>("ImagenPortada")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("VarChar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VarChar(100)");

                    b.Property<int>("NroCupos")
                        .HasColumnType("Int");

                    b.Property<int>("PrecioAsiento")
                        .HasColumnType("Integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VarChar(30)");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
